stages:
  - build
  - test

build:
  tags: [docker]
  stage: build
  image: docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    SHARED_PATH: /builds/$CI_PROJECT_PATH/mnt
  services:
    - name: docker:20.10.16-dind
  script:
    - apk update
    - apk add git make python3 py3-pip
    - cd caravel_user_project
    - source ./setup.sh
    - make setup
    - make snn
    - make user_project_wrapper
    # - make verify-neuron_test-rtl

# precheck:
#   tags: [docker]
#   stage: test
#   image: docker:20.10.16-dind
#   variables:
#     DOCKER_TLS_CERTDIR: "/certs"
#     SHARED_PATH: /builds/$CI_PROJECT_PATH/mnt
#   services:
#     - name: docker:20.10.16-dind
#   script:
#     - apk update
#     - apk add git make python3 py3-pip
#     - cd caravel_user_project
#     - source ./setup.sh
#     - make setup
