build:
  except:
   - changes:
    - README.md
    - docs/**/*
  tags: [docker]
  stage: build
  image: docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - name: docker:20.10.16-dind
  script:
    - export USER=root
    - apk update
    - apk add git make python3 py3-pip
    - cd user_adder_example
    - source ./setup.sh
    - make setup
    - make user_adder
    - make install
    - make pdk-with-volare
    - make simenv
    # - make verify-adder_test1-rtl
    # - make verify-adder_test1-gl
    - make openlane
    # - make user_adder
    - make user_project_wrapper
    - make precheck
    - make run-precheck
