build:
  except:
   changes:
    - README.md
    - docs/**/*
  tags: [docker]
  stage: build
  image: docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - name: docker:20.10.16-dind
  script:
    - apk update
    - apk add git make python3 py3-pip
    - cd user_adder_example
    - source ./setup.sh
    - make precheck
    - make setup
    - make install
    - make openlane
    - cd $(PRECHECK_ROOT) && python3 mpw_precheck.py --input_directory $(INPUT_DIRECTORY) --pdk_path $(PDK_ROOT)/$(PDK)
    - make user_adder
    - make pdk-with-volare
    - make simenv
    # - make verify-adder_test1-rtl
    # - make verify-adder_test1-gl
    # - make user_adder
    - make user_project_wrapper
    # - make run-precheck
